public class ParametersClesXlstat  {

	public static String LICENSE_ANNUELLE     = 'Annuelle';
	public static String LICENSE_PERPETUELLE  = 'Perpétuelle';
	public static String LICENSE_NETWORK      = 'Réseau';
	public static String LICENSE_SMALL_CAMPUS = 'Small Campus';
	public static String LICENSE_LARGE_CAMPUS = 'Large Campus';
	public static String LICENSE_CLASSROOM    = 'Classroom';

	public static String DOMAIN_COMPANY  = 'Company';
	public static String DOMAIN_ACADEMIC = 'Academic';
	public static String DOMAIN_CAMPUS   = 'Campus';
	public static String DOMAIN_STUDENT  = 'Student';
}